site_name: UCP
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg